### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by opt05** [VictorAlbertos/BreadcrumbsView#1]
I import the library to my app via gradle as indicated and I got this build error; `Manifest merger failed : Attribute application@allowBackup value=(false)`.

I think you should remove allowBackup attribute from your library. (Libraries should not have that attribute).

Thank you!

**Comment by VictorAlbertos** [comment]
Done! 

Try the new version 0.0.2 and let me know ;)

**Comment by opt05** [comment]
Fixed, thanks!
