### ISSUE TITLE
Horizontal separator now showing when used in nested fragment

### ISSUE THREAD

**Issue by vintrecenio** [VictorAlbertos/BreadcrumbsView#7]
When I use this in a single activity, the breadcrumbs works just fine. However, when used inside a nested fragment, the horizontal separator line does not show, only those dots are showing up. I used it inside a ConstraintLayout. In activity, it works, but not in nested fragment. Can you point out what I'm doing wrong here pls?

    <io.victoralbertos.breadcumbs_view.BreadcrumbsView
        android:id="@+id/breadcrumbs"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="@dimen/_10sdp"
        android:layout_marginRight="@dimen/_10sdp"
        android:layout_marginTop="@dimen/_20sdp"
        android:gravity="center"
        app:numberOfSteps="7"
        app:visitedStepBorderDotColor="@color/colorVisited"
        app:visitedStepFillDotColor="@color/colorVisited"
        app:nextStepBorderDotColor="@color/colorNext"
        app:nextStepFillDotColor="@color/colorNext"
        app:visitedStepSeparatorColor="@color/colorVisited"
        app:nextStepSeparatorColor="@color/colorNext"
        app:radiusDot="@dimen/radius_dot"
        app:sizeDotBorder="@dimen/size_dot_border"
        app:heightSeparator="@dimen/height_separator"
        app:layout_constraintTop_toBottomOf="@id/tvTitle"/>

**Comment by VictorAlbertos** [comment]
I have no time at this moment to investigate your issue, would you be able to investigate it and propose a solution in the form of a PR? Thanks.
